In [2]:
import numpy as np
an_array = np.array([12,23,34])
print(type(an_array))

<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [4]:
an_array[0]=888
print(an_array)

[888  23  34]


In [5]:
another = np.array([[1,2,3],[23,24,25]])
print(another)

print("accessing the shape of another",another.shape)
print("accessing the numericals[0,0] [0,1] [1,0]",another[0,0],another[0,1],another[1,0])

[[ 1  2  3]
 [23 24 25]]
accessing the shape of another (2, 3)
accessing the numericals[0,0] [0,1] [1,0] 1 2 23


In [6]:
ex4 = np.eye(2,2)
print(ex4)

[[1. 0.]
 [0. 1.]]


In [7]:
ex3 = np.full((2,0), 9.0)
print(ex3)

[]


In [8]:
ex5 = np.random.random((2,2))
print(ex5)

[[0.09091252 0.54259335]
 [0.55434738 0.56024569]]


# numpy ndarrays indexing

*chapter 2*

**Slicing**


In [9]:
a_array = np.array([[23,34,23],[34,27,34],[100,200,800]])
a_slicing = a_array[:2,1:3]
print(a_slicing)

[[34 23]
 [27 34]]


In [10]:
print("before:",a_array[0,1])
a_slicing[0,0]=1000
print("after:",a_array[0,1])

before: 34
after: 1000


In [11]:
print("before:",a_array[0,1])
a_slicing[0,0] - 1000
print("after:",a_array[0,1])

before: 1000
after: 1000


In [12]:
a_array[0,1] = 34
print("before:",a_array[0,1])
a_slicing[0,0]-1000
print("after:",a_array[0,1])

before: 34
after: 34


# use both indexing and slice indexing


In [13]:
#use both indexing and slice indexing
a_array = np.array([[23,34,23],[34,27,34],[100,200,800]])
row_rank1=a_array[1,:]
print(row_rank1)

[34 27 34]


In [14]:
#use both indexing and slice indexing
a_array = np.array([[23,34,23],[34,27,34],[100,200,800]])
row_rank2=a_array[1:2,:]
print(row_rank2,row_rank2.shape)

[[34 27 34]] (1, 3)


In [15]:
#use both indexing and slice indexing
a_array = np.array([[23,34,23],[34,27,34],[100,200,800]])
col_rank1=a_array[:,1]
print(col_rank1)

[ 34  27 200]


In [16]:
#use both indexing and slice indexing
a_array = np.array([[23,34,23],[34,27,34],[100,200,800]])
col_rank1=a_array[:,1]
print(col_rank1,row_rank2.shape)

[ 34  27 200] (1, 3)


# array indexing for changing elements


In [17]:
a_array = np.array([[23,34,23],[34,27,34],[100,200,800]])
a_indecies = np.array([[0,1,2],[10,20,30],[90,20,30]])


In [18]:
col_indicies = np.array([0,1,2,3])
print("column indicies\n",col_indicies)
row_indicies = np.arange(4)
print("row indicies\n",row_indicies)

column indicies
 [0 1 2 3]
row indicies
 [0 1 2 3]


In [19]:
for row,col in zip(row_indicies,col_indicies):
    print(row, ":", col)

0 : 0
1 : 1
2 : 2
3 : 3


In [20]:
a_array1 = np.array([row_indicies,col_indicies])
print("adding values of row and col indicies into a_array\n",a_array)

adding values of row and col indicies into a_array
 [[ 23  34  23]
 [ 34  27  34]
 [100 200 800]]


In [21]:
a_array1[:,:]+=15
print("after adding \n", a_array1)

after adding 
 [[15 16 17 18]
 [15 16 17 18]]


In [22]:
print(a_array1[:2,])

[[15 16 17 18]
 [15 16 17 18]]


In [24]:
a_slice = np.array(a_array1[:2,:])
print(a_slice)

[[15 16 17 18]
 [15 16 17 18]]


# numpy code using Boolean array


In [27]:
an_array = np.array([[11,12,13],[33,34,333],[22,222,2222]])
print(an_array)

[[  11   12   13]
 [  33   34  333]
 [  22  222 2222]]


In [29]:
# create a filter, filter is used to filter out the unnecessary terms
filter = (an_array>15)
filter

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [30]:
print(an_array[filter])

[  33   34  333   22  222 2222]


In [31]:
#for shorter version 
an_array[an_array>15]

array([  33,   34,  333,   22,  222, 2222])

In [33]:
an_array[an_array % 2 ==0] +=100
print(an_array)

[[  11  212   13]
 [  33  234  333]
 [ 222  422 2422]]


In [38]:
an_array[(an_array>20)&(an_array<200)]


array([33])

In [39]:
# arithematic operations 
ex1 = np.array([11,12,13],dtype=np.int64)
print(ex1)

[11 12 13]


In [44]:
ex2 = np.array([11.3,12.6,13.9],dtype=np.float64)
print(ex2)

[11.3 12.6 13.9]


In [45]:
print(ex1+ex2)

[22.3 24.6 26.9]


In [46]:
print(ex1-ex2)

[-0.3 -0.6 -0.9]


# Numpy, Statistical, Sorting, and Set Operations

In [51]:
arr = 10 + np.random.randn(2,5)
print(arr)

[[ 9.2861688  10.52716607  9.51490513  8.75059811 11.40227977]
 [11.39238827 10.98588205 10.13445338 10.74638983  8.62732272]]


In [52]:
print(arr.mean())

10.136755411076226


In [54]:
print(arr.mean(axis=0))

[10.33927853 10.75652406  9.82467925  9.74849397 10.01480124]


In [56]:
print(arr.sum())


101.36755411076227


In [58]:
#to compute the medians
print(np.median(arr,axis = 1))

[ 9.51490513 10.74638983]


# sorting

In [60]:
#create the 10 elements arrays of random
unsorted = np.random.randn(2,5)
print(unsorted)

[[-0.83649784  0.84237671  0.20471645 -0.67871083 -0.73980233]
 [ 0.58406301  0.13288001 -0.07116147 -0.52942062  2.60416375]]


In [64]:
#create a copy and sort
sorted = np.array(unsorted)
print(sorted)
print()
print(unsorted)

[[-0.83649784  0.84237671  0.20471645 -0.67871083 -0.73980233]
 [ 0.58406301  0.13288001 -0.07116147 -0.52942062  2.60416375]]

[[-0.83649784  0.84237671  0.20471645 -0.67871083 -0.73980233]
 [ 0.58406301  0.13288001 -0.07116147 -0.52942062  2.60416375]]


In [66]:
unsorted.sort()

print(unsorted)

[[-0.83649784 -0.73980233 -0.67871083  0.20471645  0.84237671]
 [-0.52942062 -0.07116147  0.13288001  0.58406301  2.60416375]]


# finding the unique elements

In [68]:
a=np.array([12,22,12,333,12,34])

print(np.unique(a))

[ 12  22  34 333]


# set operations with np.array data type

In [69]:
s1 = np.array(['sit','desk','punch'])
s2=np.array(['eat','sit','jump','punch'])
print(s1,s2)

['sit' 'desk' 'punch'] ['eat' 'sit' 'jump' 'punch']


In [71]:
print(np.intersect1d(s1,s2))

['punch' 'sit']


In [72]:
print(np.union1d(s1,s2))

['desk' 'eat' 'jump' 'punch' 'sit']


In [74]:
print(np.setdiff1d(s1,s2))

['desk']


In [75]:
print(np.in1d(s1,s2))

[ True False  True]


# Broadcasting

In [80]:
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [85]:
add_rows = np.array([1,0,3])
print(add_rows)

[1 0 3]


In [86]:
y = start + add_rows
print(y)

[[1. 0. 3.]
 [1. 0. 3.]
 [1. 0. 3.]
 [1. 0. 3.]]


In [87]:
add_cols = np.array([[1,0,3,4]])
add_cols = add_cols.T
print(add_cols)

[[1]
 [0]
 [3]
 [4]]


In [90]:
#add to each column of 'start' using broadcasting
y = start + add_cols
print(y)

[[1. 1. 1.]
 [0. 0. 0.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [91]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# speed test: ndarrys vs list

* First setup parameter for speed test. well be testing time for some elements in the ndarray versus list


In [95]:
from numpy import arange
from timeit import Timer


size=1000000
timeits=1000


In [96]:
#create the ndarray with the values [1,2,3,4,......,size]
ndarray = arange(size)
print(type(ndarray))

<class 'numpy.ndarray'>


In [103]:
# timer expects operations as parameter.
#here we can pass ndarray.sum()

timer_numpy = Timer("ndarray.sum()","from __main__ import ndarray")

print("time taken by ndarray: %f seconds" %
      (timer_numpy.timeit(timeits)/timeits))

time taken by ndarray: 0.000451 seconds


In [104]:
#create a list with the values 1,2,3,4,....,size-1

a_list = list(range(size))
print(type(a_list))

<class 'list'>


In [105]:
# timer expects operations as parameter.
#here we can pass a_list

timer_list = Timer("sum(a_list)","from __main__ import a_list")

print("time taken by ndarray: %f seconds" %
      (timer_numpy.timeit(timeits)/timeits))

time taken by ndarray: 0.000460 seconds
